- hosts: all
  gather_facts: no
  connection: local
  
  tasks:
  - name: Check that you can connect (GET) to a page and it returns a status 200
    uri:
      url: https://httpbin.org/post
      method: POST
      body_format: form-multipart
      body:
        file1:
          filename: /bin/true
          mime_type: application/octet-stream
        file2:
          content: text based file content
          filename: fake.txt
          mime_type: text/plain
        text_form_field: value

  - name: run this command and ignore the result
    shell: /usr/bin/pwd || /bin/true

    register: rs

  - debug:
      var: rs
