- hosts: all
  gather_facts: no
  
  tasks:
  - name: Check that you can connect (GET) to a page and it returns a status 200
    shell: pkill -9 stress
    register: pkill_rs

  - debug:
      var: pkill_rs
