
###############  ADMIN CLUSTER admin.conf  ###############
[admin_cluster_master]
; 10.12.44.93
192.168.64.18
##########################################################

[byoh_node_active]
; 10.12.44.93
; 10.12.44.94
; 10.12.44.95
; 10.12.44.96
; 10.12.44.97
192.168.64.18

[byoh_node_new]

[byoh_nodes:children]
byoh_node_active
byoh_node_new

[byoh_node_new:vars]
# admin 클러스터
; admin_cluster_control_vip="10.12.44.93"
; admin_cluster_master_node_ip="10.12.44.93"

admin_cluster_control_vip="192.168.64.18"
admin_cluster_master_node_ip="192.168.64.18"

mgmt_namespace="gaia-ansible-test"
infra="dev"
#mgmt_user="ktcloud"
#mgmt_pass="Nextktc1!"

# BYOH agent 변수
byoh_agent_url="https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/releases/download/v0.5.0/byoh-hostagent-linux-amd64"
byoh_agent_path="/usr/local/bin/byoh-agent"
target_dir="/etc/byoh-agent/mgmt"
target_file="kubeconfig"
